const translations = {
  ar: {
    mainTitle: 'Doc_HEMA Team',
    declineBin: 'رفض BIN',
    activeBin: 'BIN نشط',
    autoTry: 'تشغيل المحاولة التلقائية (Auto Try)',
    addBin: 'إضافة BIN',
    quickUse: 'استخدام BIN في النموذج',
    setting: 'الإعدادات',
    cardAutoSave: 'حفظ البطاقة تلقائيًا',
    activeBinLabel: 'Active BIN',
    declineBinLabel: 'Decline BIN',
    saveBtn: 'حفظ BIN',
    addBinSection: 'إضافة BIN جديد',
    quickBinSection: 'استخدام BIN سريع',
    savedBinsSection: 'BINs المحفوظة',
    newBinInputLabel: 'رقم BIN (6-16 رقم، استخدم X للمجهول)',
    newBinInputPh: 'مثال: 123456XXXXXX1234',
    newCardNumberLabel: 'رقم البطاقة الكامل (اختياري)',
    newCardNumberPh: '1234567890123456',
    newExpiryDateLabel: 'تاريخ الانتهاء (اختياري)',
    newExpiryDatePh: 'MM/YY',
    newCvcLabel: 'CVC (اختياري)',
    newCvcPh: '123',
    newBinNameLabel: 'اسم BIN (اختياري)',
    newBinNamePh: 'اسم البطاقة',
    binHelp: 'استخدم X للأرقام المجهولة، سيتم توليد أرقام عشوائية. إذا أدخلت رقم بطاقة كامل سيتم استخدامه.',
    quickBinInputLabel: 'أدخل BIN للاستخدام السريع',
    quickBinInputPh: 'BIN سريع (6-16 رقم)',
    quickBinHelp: 'سيتم توليد البيانات وملؤها مباشرة في فيسبوك',
    cardAutoSaveLabel: 'حفظ البطاقة تلقائيًا',
    activeBinInputLabel: 'Active BIN',
    activeBinInputPh: 'أدخل Active BIN',
    expireActiveDateInputLabel: 'تاريخ انتهاء Active BIN',
    expireActiveDateInputPh: 'MMYY',
    activeCvvInputLabel: 'Active BIN CVV',
    activeCvvInputPh: 'CVV',
    declineBinInputLabel: 'Decline BIN',
    declineBinInputPh: 'أدخل Decline BIN',
    expireDeclineDateInputLabel: 'تاريخ انتهاء Decline BIN',
    expireDeclineDateInputPh: 'MMYY',
    declineCvvInputLabel: 'Decline BIN CVV',
    declineCvvInputPh: 'CVV',
    saveBinBtn: 'حفظ BIN',
    useBtn: 'استخدام',
    deleteBtn: 'حذف',
    fullNumberIndicator: 'رقم كامل',
    expiryIndicator: 'تاريخ',
    cvcIndicator: 'CVC',
    noSavedBins: 'لا توجد BINs محفوظة',
    logsEmpty: 'لا يوجد عمليات بعد.',
    shortcutDecline: 'اختصار: Ctrl+Shift+X',
    shortcutActive: 'اختصار: Ctrl+Shift+V',
    madeBy: '(Made by Doc_HEMA)',
    enterBin: 'يرجى إدخال رقم BIN',
    binLength: 'يجب أن يكون طول BIN من 6 إلى 16 رقم',
    binPattern: 'يجب أن يحتوي BIN على أرقام و X فقط',
    cardNumberLength: 'رقم البطاقة يجب أن يكون 16 رقم',
    expiryFormat: 'صيغة التاريخ غير صحيحة (MM/YY)',
    cvcLength: 'CVC يجب أن يكون 3 أرقام',
    binAdded: bin => `تم إضافة BIN: ${bin}`,
    binUsed: bin => `تم استخدام BIN: ${bin}`,
    binDeleted: bin => `تم حذف BIN: ${bin}`,
    binNotFound: 'لم يتم العثور على BIN',
    quickBinSuccess: (bin, number, expiry, cvc) => `BIN ${bin}: ${number} | التاريخ: ${expiry} | CVC: ${cvc}`,
    error: 'حدث خطأ',
    success: 'تمت العملية بنجاح',
    autoSaveOn: '✅ Auto Save مفعل',
    autoSaveOff: '❌ Auto Save معطل',
    activeTryIntervalLabel: 'الفاصل الزمني (ثواني)',
    activeTryCountLabel: 'عدد المحاولات',
  },
  en: {
    mainTitle: 'Doc_HEMA Team',
    declineBin: 'Decline Bin',
    activeBin: 'Active Bin',
    autoTry: 'Enable Auto Try',
    addBin: 'Add BIN',
    quickUse: 'Use BIN in Form',
    setting: 'Settings',
    cardAutoSave: 'Card Auto Save',
    activeBinLabel: 'Active BIN',
    declineBinLabel: 'Decline BIN',
    saveBtn: 'Save Bin',
    addBinSection: 'Add New BIN',
    quickBinSection: 'Quick BIN Use',
    savedBinsSection: 'Saved BINs',
    newBinInputLabel: 'BIN Number (6-16 digits, use X for unknown)',
    newBinInputPh: 'e.g. 123456XXXXXX1234',
    newCardNumberLabel: 'Full Card Number (optional)',
    newCardNumberPh: '1234567890123456',
    newExpiryDateLabel: 'Expiry Date (optional)',
    newExpiryDatePh: 'MM/YY',
    newCvcLabel: 'CVC (optional)',
    newCvcPh: '123',
    newBinNameLabel: 'BIN Name (optional)',
    newBinNamePh: 'Card Name',
    binHelp: 'Use X for unknown digits, random numbers will be generated. If you enter a full card number, it will be used instead.',
    quickBinInputLabel: 'Enter BIN for quick use',
    quickBinInputPh: 'Quick BIN (6-16 digits)',
    quickBinHelp: 'Data will be generated and filled directly in Facebook',
    cardAutoSaveLabel: 'Card Auto Save',
    activeBinInputLabel: 'Active BIN',
    activeBinInputPh: 'Enter Active BIN',
    expireActiveDateInputLabel: 'Active BIN Expire Date',
    expireActiveDateInputPh: 'MMYY',
    activeCvvInputLabel: 'Active BIN CVV',
    activeCvvInputPh: 'CVV',
    declineBinInputLabel: 'Decline BIN',
    declineBinInputPh: 'Enter Decline BIN',
    expireDeclineDateInputLabel: 'Decline BIN Expire Date',
    expireDeclineDateInputPh: 'MMYY',
    declineCvvInputLabel: 'Decline BIN CVV',
    declineCvvInputPh: 'CVV',
    saveBinBtn: 'Save Bin',
    useBtn: 'Use',
    deleteBtn: 'Delete',
    fullNumberIndicator: 'Full Number',
    expiryIndicator: 'Expiry',
    cvcIndicator: 'CVC',
    noSavedBins: 'No saved BINs',
    logsEmpty: 'No operations yet.',
    shortcutDecline: 'Shortcut: Ctrl+Shift+X',
    shortcutActive: 'Shortcut: Ctrl+Shift+V',
    madeBy: '(Made by Doc_HEMA)',
    enterBin: 'Please enter a BIN number',
    binLength: 'BIN length must be 6 to 16 digits',
    binPattern: 'BIN must contain only numbers and X',
    cardNumberLength: 'Card number must be 16 digits',
    expiryFormat: 'Invalid date format (MM/YY)',
    cvcLength: 'CVC must be 3 digits',
    binAdded: bin => `BIN added: ${bin}`,
    binUsed: bin => `BIN used: ${bin}`,
    binDeleted: bin => `BIN deleted: ${bin}`,
    binNotFound: 'BIN not found',
    quickBinSuccess: (bin, number, expiry, cvc) => `BIN ${bin}: ${number} | Expiry: ${expiry} | CVC: ${cvc}`,
    error: 'An error occurred',
    success: 'Operation successful',
    autoSaveOn: '✅ Auto Save ON',
    autoSaveOff: '❌ Auto Save OFF',
    activeTryIntervalLabel: 'Interval (seconds)',
    activeTryCountLabel: 'Try Count',
  },
  bn: {
    mainTitle: 'Doc_HEMA Team',
    declineBin: 'বিন বাতিল করুন',
    activeBin: 'সক্রিয় BIN',
    autoTry: 'অটো ট্রাই চালু করুন',
    addBin: 'BIN যোগ করুন',
    quickUse: 'ফর্মে BIN ব্যবহার করুন',
    setting: 'সেটিংস',
    cardAutoSave: 'কার্ড অটো সেভ',
    activeBinLabel: 'সক্রিয় BIN',
    declineBinLabel: 'বাতিল BIN',
    saveBtn: 'BIN সংরক্ষণ করুন',
    addBinSection: 'নতুন BIN যোগ করুন',
    quickBinSection: 'দ্রুত BIN ব্যবহার',
    savedBinsSection: 'সংরক্ষিত BINs',
    newBinInputLabel: 'BIN নম্বর (6-16 সংখ্যা, অজানা জন্য X ব্যবহার করুন)',
    newBinInputPh: 'উদাহরণ: 123456XXXXXX1234',
    newCardNumberLabel: 'সম্পূর্ণ কার্ড নম্বর (ঐচ্ছিক)',
    newCardNumberPh: '1234567890123456',
    newExpiryDateLabel: 'মেয়াদ শেষের তারিখ (ঐচ্ছিক)',
    newExpiryDatePh: 'MM/YY',
    newCvcLabel: 'CVC (ঐচ্ছিক)',
    newCvcPh: '123',
    newBinNameLabel: 'BIN নাম (ঐচ্ছিক)',
    newBinNamePh: 'কার্ডের নাম',
    binHelp: 'অজানা সংখ্যার জন্য X ব্যবহার করুন, র্যান্ডম সংখ্যা তৈরি হবে। আপনি যদি সম্পূর্ণ কার্ড নম্বর দেন, সেটি ব্যবহৃত হবে।',
    quickBinInputLabel: 'দ্রুত ব্যবহারের জন্য BIN লিখুন',
    quickBinInputPh: 'দ্রুত BIN (6-16 সংখ্যা)',
    quickBinHelp: 'ডেটা তৈরি হবে এবং সরাসরি ফেসবুকে পূরণ হবে',
    cardAutoSaveLabel: 'কার্ড অটো সেভ',
    activeBinInputLabel: 'সক্রিয় BIN',
    activeBinInputPh: 'সক্রিয় BIN লিখুন',
    expireActiveDateInputLabel: 'সক্রিয় BIN মেয়াদ শেষের তারিখ',
    expireActiveDateInputPh: 'MMYY',
    activeCvvInputLabel: 'সক্রিয় BIN CVC',
    activeCvvInputPh: 'CVV',
    declineBinInputLabel: 'বাতিল BIN',
    declineBinInputPh: 'বাতিল BIN লিখুন',
    expireDeclineDateInputLabel: 'বাতিল BIN মেয়াদ শেষের তারিখ',
    expireDeclineDateInputPh: 'MMYY',
    declineCvvInputLabel: 'বাতিল BIN CVC',
    declineCvvInputPh: 'CVV',
    saveBinBtn: 'BIN সংরক্ষণ করুন',
    useBtn: 'ব্যবহার করুন',
    deleteBtn: 'মুছুন',
    fullNumberIndicator: 'সম্পূর্ণ নম্বর',
    expiryIndicator: 'মেয়াদ',
    cvcIndicator: 'CVC',
    noSavedBins: 'কোনও সংরক্ষিত BIN নেই',
    logsEmpty: 'এখনও কোনও অপারেশন নেই।',
    shortcutDecline: 'শর্টকাট: Ctrl+Shift+X',
    shortcutActive: 'শর্টকাট: Ctrl+Shift+V',
    madeBy: '(Doc_HEMA দ্বারা তৈরি)',
    enterBin: 'অনুগ্রহ করে BIN নম্বর লিখুন',
    binLength: 'BIN দৈর্ঘ্য 6 থেকে 16 সংখ্যা হতে হবে',
    binPattern: 'BIN শুধুমাত্র সংখ্যা এবং X থাকতে হবে',
    cardNumberLength: 'কার্ড নম্বর 16 সংখ্যা হতে হবে',
    expiryFormat: 'ভুল তারিখ ফরম্যাট (MM/YY)',
    cvcLength: 'CVC 3 সংখ্যা হতে হবে',
    binAdded: bin => `BIN যোগ হয়েছে: ${bin}`,
    binUsed: bin => `BIN ব্যবহৃত হয়েছে: ${bin}`,
    binDeleted: bin => `BIN মুছে ফেলা হয়েছে: ${bin}`,
    binNotFound: 'BIN পাওয়া যায়নি',
    quickBinSuccess: (bin, number, expiry, cvc) => `BIN ${bin}: ${number} | মেয়াদ: ${expiry} | CVC: ${cvc}`,
    error: 'একটি ত্রুটি ঘটেছে',
    success: 'অপারেশন সফল হয়েছে',
    autoSaveOn: '✅ অটো সেভ চালু',
    autoSaveOff: '❌ অটো সেভ বন্ধ',
    activeTryIntervalLabel: 'ইন্টারভাল (সেকেন্ড)',
    activeTryCountLabel: 'চেষ্টা সংখ্যা',
  }
};

document.addEventListener('DOMContentLoaded', () => {
  // هنا تضع كل الكود الخاص بواجهة الإعدادات مثل القيود على الحقول، تحميل القيم، إلخ
  // إذا كان هناك كود معطل بسبب التعليق السابق، أعد تفعيله هنا
}); 